name: Lint

on:
  push:
  pull_request:

jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: chartboost/ruff-action@v1
        name: Run Ruff
